apiVersion: v1
kind: Pod
metadata:
  name: sample-app1
  namespace: default
  labels:
    environment: production
    app: sample-app1
spec:
  volumes:
    - name: sample-app1-volume
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - name: sample-app1
      image: us.gcr.io/myproject36539/kube-volume-examples:1.0
      volumeMounts:
        - name: sample-app1-volume
          mountPath: /data
          readOnly: false

