apiVersion: v1
kind: Service
metadata:
  name: service1-nodeport
spec:
  selector:
    environment: production
    app: service1
  type: NodePort
  ports:
    - nodePort: 31000 # Expose port to external clients
      port: 80 # Kubernetes service port
      targetPort: 8080 # Application port