apiVersion: v1
kind: PersistentVolume
metadata:
  name: service1-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mydisk-1
    fsType: ext4